#!/usr/bin/env python3
"""
tracking_test.py - tracking_guidance.py (ArduPilot FOLLOW law) OFFLINE TESTS
============================================================= NO SIM REQUIRED. Two layers:

  UNIT: Port of ArduPilot mathematics (sqrt_controller), LOS/prediction geometry, clamps of the rate
  law, offset melting, yaw. OFF: mpc_test. Closed loop with emulation -- SAME engine, SAME skeleton
  LOOP emulation (LPF 0.35, speed clamp, acceleration limited autopilot, true virtual gimbal). So
  the numbers measured with the MPC can be directly compared.

Harness: cd guidance_allstar && python3 tracking_test.py [--fast-value]
"""

from __future__ import annotations

import argparse
import math
import sys
import time
from pathlib import Path

import numpy as np

_HERE = str(Path(__file__).resolve().parent)
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

from visual_base import Measurement                              # noqa: E402
from tracking_guidance import (TrackingConfig, TrackingController, los_triad,  # noqa: E402
                         sqrt_controller, sqrt_controller_2d)
import mpc_test                                                # noqa: E402
from mpc_test import Simulation, SCAFFOLD_SPEED_CEILING              # noqa: E402

PASS = []
FAILED = []


def _report_value(label_item, complete, ek=""):
    (PASS if complete else FAILED).append(label_item)
    print(f"  [{'OK ' if complete else 'ERROR'}] {label_item}{(' -- ' + ek) if ek else ''}")
    return complete


def _measurement(ex=0.0, ey=0.0, r=40.0, t=0.0, dt=0.05, pos=(0.0, 0.0, -60.0),
           vel=(20.0, 0.0, 0.0), yaw=0.0, age_value=0.0, vibe=None, area_value=40.0):
    return Measurement(t=t, dt=dt, ex_deg=ex, ey_deg=ey, bbox_w=area_value, bbox_h=area_value,
                 area_root=area_value, coverage_pct=None, bbox_age_s=age_value, range_m_value=r,
                 pos_ned=np.array(pos, dtype=float),
                 vel_ned=np.array(vel, dtype=float),
                 yaw_rad=yaw, roll_rad=0.0, pitch_rad=0.0, vibe_max=vibe)


# ================================================ 0. ORTAK MOTOR MUHURU

def test_motor_seal():
    """HAS THE JOINT TESTING FACILITY (mpc_test. Simulation) CHANGED?

    WHY IT EXISTS: all closed loop numbers of this file are generated by the mpc_test.Simulation
    engine. That engine DOES NOT belong to MPC -- point-mass fighter + virtual gimbal + skeletal
    imitation, so the COMMON ground of both laws; it just sits historically in MPC's file. If
    another agent changes those constants while working on MPC (the TO_TEST clause 10 suggests
    exactly this: the actuator model tau) all the reference numbers there will SILENTLY shift and
    the regression tests will lie.

    This test breaks that silence: if the engine physics changes, HERE explodes and says the tables
    at ARDUPILOT_TRACKING.md need to be remeasured. FAILURE = 'engine changed, refresh numbers'; NOT
    error."""
    print("\n0. Ortak motor seal (mpc_test.Simulation fizigi)")
    expected_value = {
        'SCAFFOLD_SPEED_CEILING': (SCAFFOLD_SPEED_CEILING, 35.0),
        'SCAFFOLD_CLIMB_MPS': (mpc_test.SCAFFOLD_CLIMB_MPS, 10.0),
        'SCAFFOLD_DESCENT_MPS': (mpc_test.SCAFFOLD_DESCENT_MPS, 5.0),
        'LOSS_FINISH_S': (mpc_test.LOSS_FINISH_S, 1.5),
        'Simulation.ACCELERATION_HORIZONTAL': (Simulation.ACCELERATION_HORIZONTAL, 5.0),
        'Simulation.ACCELERATION_VERTICAL': (Simulation.ACCELERATION_VERTICAL, 5.0),
        'Simulation.YAW_SLEW_DPS2': (Simulation.YAW_SLEW_DPS2, 120.0),
        'Simulation.YAW_LPF_TAU': (Simulation.YAW_LPF_TAU, 0.15),
        'Simulation.PITCH_CLIMB': (Simulation.PITCH_CLIMB, 2.6),
    }
    shifted = [f"{label_item}: {measure_value} != {bek}" for label_item, (measure_value, bek) in expected_value.items()
              if abs(float(measure_value) - bek) > 1e-9]
    complete = _report_value("0a motor constants are unchanged", not shifted,
                   '; '.join(shifted) if shifted else
                   f"{len(expected_value)} fixed unchanged")
    # gimbal_camera DEFAULT: True in gimbal branch. If it changes, the entire ARDUPILOT_TRACKING.md 6e table
    # (law vs physics 2x2) should be re-read.
    import inspect
    gk = inspect.signature(Simulation.__init__).parameters['gimbal_camera'].default
    complete &= _report_value("0b gimbal_camera default True (gimbal branch)",
                    gk is True, f"default={gk}")
    return complete


# ======================================================= 1. ArduPilot matematigi

def test_sqrt_controller():
    """Are all three arms of the AP_Math/control.cpp port correct?"""
    print("\n1. sqrt_controller (AP_Math/control.cpp portu)")
    complete = True

    # (a) pure P if there is no second-order ceiling
    complete &= _report_value("1a ceiling= 0 -> pure P",
                    abs(sqrt_controller(10.0, 0.5, 0.0, 0.1) - 5.0) < 1e-9)

    # (b) p= 0 -> pure sqrt ( 2 *a*x)
    expected_value = math.sqrt(2.0 * 2.5 * 20.0)
    v = sqrt_controller(20.0, 0.0, 2.5, 0.0)
    complete &= _report_value("1b p=0 -> sqrt(2*a*x)", abs(v - expected_value) < 1e-9,
                    f"{v:.3f} m/s")

    # (c) hybrid: linear region |x| <a/p^2, outside handle sqrt
    p, a = 1.0, 2.5
    linear = a / (p * p)                      # 2.5 m
    ic = sqrt_controller(1.0, p, a, 0.0)
    dis = sqrt_controller(25.0, p, a, 0.0)
    dis_bek = math.sqrt(2.0 * a * (25.0 - linear / 2.0))
    complete &= _report_value("1c hybrid arms",
                    abs(ic - 1.0) < 1e-9 and abs(dis - dis_bek) < 1e-9,
                    f"inside={ic:.2f} outside={dis:.2f} (linear limit {linear:.1f} m)")

    # (d) sign aspect
    complete &= _report_value("1d odd function (with inverse sign)",
                    abs(sqrt_controller(-25.0, p, a, 0.0) + dis) < 1e-9)

    # (e) dt clamp: overcoming error in one step
    v = sqrt_controller(0.1, 10.0, 0.0, 0.05)   # P output 1.0, limit 0.1/0.05=2
    v2 = sqrt_controller(0.1, 100.0, 0.0, 0.05)  # P output is clipped to 10 -> 2
    complete &= _report_value("1e dt clamp", abs(v - 1.0) < 1e-9 and abs(v2 - 2.0) < 1e-9,
                    f"{v:.2f} / {v2:.2f} m/s")

    # (f) 2D form preserves orientation
    e = np.array([3.0, 4.0])
    v2d = sqrt_controller_2d(e, 1.0, 2.5, 0.0)
    direction_error = abs(float(np.cross(e / 5.0, v2d)))
    complete &= _report_value("1f 2D direction conservation", direction_error < 1e-9,
                    f"|v|={np.linalg.norm(v2d):.2f}")
    return complete


# ========================================================= 2. Vision -> target location

def test_target_estimation():
    """ex/ey/range -> target NED location; Step that replaces AP_Follow."""
    print("\n2. Target estimation (vision + range -> NED)")
    complete = True
    k = TrackingController(TrackingConfig())

    # (a) nose to the north, target straight ahead and at equal altitude
    o = _measurement(ex=0.0, ey=0.0, r=50.0, yaw=0.0, pos=(0.0, 0.0, -60.0))
    target_value, u = k._target_estimate(o, 50.0, 0.0, 0.0)
    complete &= _report_value("2a right ahead", np.allclose(target_value, [50.0, 0.0, -60.0], atol=1e-6),
                    f"{np.round(target_value, 2).tolist()}")

    # (b) ex=+30 -> target is on the RIGHT (east is at yaw=0)
    target_value, u = k._target_estimate(o, 50.0, 30.0, 0.0)
    complete &= _report_value("2b ex>0 -> right",
                    target_value[1] > 24.9 and abs(target_value[0] - 43.3) < 0.1,
                    f"{np.round(target_value, 2).tolist()}")

    # (c) eps=+20 (target UP) -> NED z REDUCES (altitude increases)
    target_value, u = k._target_estimate(o, 50.0, 0.0, 20.0)
    complete &= _report_value("2c eps>0 -> target above",
                    abs(target_value[2] - (-60.0 - 50.0 * math.sin(math.radians(20)))) < 1e-6,
                    f"z={target_value[2]:.2f} (altitude {-target_value[2]:.1f} m)")

    # (d) Turning with yaw: if the nose is facing east, ex=0 puts the target EAST
    o2 = _measurement(yaw=math.radians(90.0))
    target_value, u = k._target_estimate(o2, 50.0, 0.0, 0.0)
    complete &= _report_value("2d yaw cevrimi", np.allclose(target_value, [0.0, 50.0, -60.0], atol=1e-6),
                    f"{np.round(target_value, 2).tolist()}")

    # (e) REVERSE SOLUTION: ex / eps should give the same point (pure geometry except gimbal chain) in
    # back estimation generated from random targets.
    rng = np.random.default_rng(7)
    worst_value = 0.0
    for _ in range(200):
        pos = rng.normal(0.0, 100.0, 3)
        yaw = rng.uniform(-math.pi, math.pi)
        d = rng.normal(0.0, 40.0, 3)
        r = float(np.linalg.norm(d))
        if r < 1.0:
            continue
        c, s = math.cos(yaw), math.sin(yaw)
        dh = np.array([c * d[0] + s * d[1], -s * d[0] + c * d[1], d[2]])
        ex = math.degrees(math.atan2(dh[1], dh[0]))
        eps = math.degrees(math.atan2(-dh[2], math.hypot(dh[0], dh[1])))
        o3 = _measurement(pos=tuple(pos), yaw=yaw)
        target_value, _ = k._target_estimate(o3, r, ex, eps)
        worst_value = max(worst_value, float(np.linalg.norm(target_value - (pos + d))))
    complete &= _report_value("2e inverse solution (200 random)", worst_value < 1e-9,
                    f"biggest error {worst_value:.2e} m")
    return complete


# ========================================================= 3. speed law handcuffs

def test_speed_law():
    """ModeFollow::run() sequence: P -> horizontal scale -> vertical clamp -> brake."""
    print("\n3. Rate law (sequence mode_follow.cpp)")
    complete = True

    # (a) classical arm pure P (with 'p' speed source -- mode_follow itself)
    k = TrackingController(TrackingConfig(kp=0.5, braking='disabled', speed_source='p'))
    v, kel, _ = k._speed_law(np.array([20.0, 0.0, 0.0]), 20.0, 0.05)
    complete &= _report_value("3a classic = kp*error", abs(v[0] - 10.0) < 1e-9, f"{v[0]:.2f} m/s")

    # (b) horizontal ceiling: DIRECTION IS PRESERVED
    k = TrackingController(TrackingConfig(kp=1.0, speed_ceiling_mps=35.0, braking='disabled',
                                 speed_source='p'))
    v, kel, _ = k._speed_law(np.array([60.0, 60.0, 0.0]), 84.85, 0.05)
    horizontal = math.hypot(v[0], v[1])
    complete &= _report_value("3D horizontal ceiling + direction preservation",
                    abs(horizontal - 35.0) < 1e-6 and abs(v[0] - v[1]) < 1e-9 and kel,
                    f"|v_xy|={horizontal:.2f}")

    # (c) vertical ceilings asymmetrical (WPNAV_SPEED_UP 10 / _DN 5)
    v, _, _ = k._speed_law(np.array([0.0, 0.0, -50.0]), 0.0, 0.05)
    v2, _, _ = k._speed_law(np.array([0.0, 0.0, 50.0]), 0.0, 0.05)
    complete &= _report_value("3c vertical ceiling 10 up / 5 down",
                    abs(v[2] + 10.0) < 1e-9 and abs(v2[2] - 5.0) < 1e-9,
                    f"{v[2]:.1f} / {v2[2]:.1f} m/s")

    # (d) BRAKE CLOSED vs OPEN: 25 ceiling at m = sqrt(2*2.5*(25-1.25)) = 10.90
    k_disabled = TrackingController(TrackingConfig(kp=1.0, braking='disabled', speed_source='p'))
    k_enabled = TrackingController(TrackingConfig(kp=1.0, braking='ap', speed_source='p'))
    k_enabled._last_error_z = 0.0
    error_value = np.array([25.0, 0.0, 0.0])
    v_k, _, _ = k_disabled._speed_law(error_value, 25.0, 0.05)
    v_a, _, ft = k_enabled._speed_law(error_value, 25.0, 0.05)
    expected_value = math.sqrt(2.0 * (0.5 * 5.0) * (25.0 - (0.5 * 5.0) / 2.0))
    complete &= _report_value("3d brake: 25 10.90 m/s roof (ON), 25 in closed",
                    abs(v_k[0] - 25.0) < 1e-6 and abs(v_a[0] - expected_value) < 1e-6,
                    f"closed={v_k[0]:.2f} open={v_a[0]:.2f} (ceiling {ft:.2f})")

    # (e) REASON FOR BRAKE: target speed (21 m/s) cannot be reached when open
    complete &= _report_value("21 m/s target cannot be captured if 3e brake is on (must be OFF)",
                    v_a[0] < 21.05 < v_k[0],
                    f"brake ceiling {v_a[0]:.1f} < target 21.05 < free {v_k[0]:.1f}")

    # (f) 'range' lever: far brake ON, near OFF
    k_m = TrackingController(TrackingConfig(kp=1.0, braking='range_value', braking_range_m=45.0,
                                   speed_source='p'))
    k_m._last_error_z = 0.0
    v_far, _, _ = k_m._speed_law(np.array([60.0, 0.0, 0.0]), 60.0, 0.05)
    v_near, _, _ = k_m._speed_law(np.array([25.0, 0.0, 0.0]), 25.0, 0.05)
    complete &= _report_value("3f 'range' lever (45 m threshold)",
                    v_far[0] < 20.0 and abs(v_near[0] - 25.0) < 1e-6,
                    f"60 m -> {v_far[0]:.1f}, 25 m -> {v_near[0]:.1f} m/s")

    # (g) poscon handle: SLOWER than classic outside linear region
    k_p = TrackingController(TrackingConfig(law='poscon', braking='disabled', speed_source='p'))
    v_p, _, _ = k_p._speed_law(np.array([25.0, 0.0, 0.0]), 25.0, 0.05)
    complete &= _report_value("3g poscon (Copter>=4.5) sqrt kolu",
                    5.0 < v_p[0] < 20.0 and v_p[0] < v_k[0],
                    f"poscon={v_p[0]:.2f} vs classical={v_k[0]:.2f} m/s")

    # (h) speed_source='ceiling' (DEFAULT): magnitude INDEPENDENT of range, direction does not change --
    # direction/speed separation of plane_follow.
    k_t = TrackingController(TrackingConfig(braking='disabled'))       # default ceiling
    v_far, _, _ = k_t._speed_law(np.array([60.0, 0.0, 0.0]), 60.0, 0.05)
    v_near, _, _ = k_t._speed_law(np.array([5.0, 0.0, 0.0]), 5.0, 0.05)
    v_tilted, _, _ = k_t._speed_law(np.array([10.0, 10.0, 0.0]), 14.14, 0.05)
    complete &= _report_value("3h 'ceiling': speed independent of range, direction maintained",
                    abs(v_far[0] - 35.0) < 1e-6 and abs(v_near[0] - 35.0) < 1e-6
                    and abs(v_tilted[0] - v_tilted[1]) < 1e-9,
                    f"60 m -> {v_far[0]:.1f}, 5 m -> {v_near[0]:.1f} m/s")

    # (i) acceleration shaping: trims the increment of the command SIZE
    k_s = TrackingController(TrackingConfig(braking='disabled', acceleration_shaping_mps2=2.0))
    k_s._last_v_ned = np.array([17.0, 0.0, 0.0])
    v_s, _, _ = k_s._speed_law(np.array([60.0, 0.0, 0.0]), 60.0, 0.05)
    complete &= _report_value("3i acceleration shaping ( 2 m/s ^ 2 , dt= 0.05 -> + 0.1 m/s )",
                    abs(float(np.linalg.norm(v_s)) - 17.1) < 1e-6,
                    f"|v|={float(np.linalg.norm(v_s)):.2f} m/s")
    return complete


# ========================================================= 4 . kp justification (deviation 2 )

def test_kp_rationale():
    """Why can't PURE mode_follow (|v| = kp*error) hit a MOVING target?

    Analytics: since target speed feedforward is PROHIBITED, the P term alone has to provide ALL the
    target speed. Balance d* = v_target / kp; At that distance the command becomes exactly equal to
    the target speed and the range FREEZES. The test shows both arithmetic and closed loop."""
    print("\n4. 'p' speed source (pure mode_follow) -- balance distance")
    complete = True
    result_value = {}
    for kp in (0.1, 0.35, 1.0, 3.0):
        d_balance = 21.05 / kp
        saturation_range = SCAFFOLD_SPEED_CEILING / kp      # ceiling contact distance
        result_value[kp] = (d_balance, saturation_range)
        print(f"      kp= {kp:<5.2f} balance distance= {d_balance:7.1f} m   "
              f"saturation to ceiling={saturation_range:6.1f} m")
    complete &= _report_value("4a AP default kp=0.1 -> 210 m remains balanced",
                    result_value[0.1][0] > 200.0,
                    "engagement envelope (handoff <=60 m) completely outside")

    # CLOSED LOOP: theory says d*=21.05 m, what does the engine say?
    s = scenario_run(route="straight", handoff="tail", target_speed_mps=21.05, seed_value=3,
                    duration_value=30.0, config_value=TrackingConfig(speed_source='p', kp=1.0))
    print(f"      closed loop (kp=1.0, 'p'): min range {s['min_r']:.2f} m "
          f"(theory {result_value[1.0][0]:.1f} m), shutdown {s['closure_mean']:+.1f} m/s")
    complete &= _report_value("4b confirms the closed loop theory (equilibrium ~21 m)",
                    abs(s['min_r'] - result_value[1.0][0]) < 6.0,
                    f"measured {s['min_r']:.2f} m vs theory {result_value[1.0][0]:.1f} m")

    # DEFAULT arm ('ceiling') should break the wall in the same scenario
    s2 = scenario_run(route="straight", handoff="tail", target_speed_mps=21.05, seed_value=3,
                     duration_value=30.0, config_value=TrackingConfig())
    print(f"      closed loop ('ceiling'): min range {s2['min_r']:.2f} m, "
          f"end={s2['finish']}, close {s2['closure_mean']:+.1f} m/s")
    complete &= _report_value("4c Arm ' ceiling_value ' breaks the balance wall",
                    s2['min_r'] < 0.5 * s['min_r'],
                    f"{s['min_r']:.1f} m -> {s2['min_r']:.2f} m")
    return complete


# ========================================================= 5. Offset and yaw

def test_offset_and_yaw():
    print("\n5. Offset melt (FOLL_OFS) and yaw (FOLL_YAW_BEHAVE=0)")
    complete = True
    k = TrackingController(TrackingConfig(ofs_backward_m=25.0, ofs_down_m=6.0))
    u = np.array([1.0, 0.0, 0.0])
    ofs_far, scale_far = k._offset(u, 60.0)
    ofs_middle, scale_middle = k._offset(u, 35.0)
    ofs_near, scale_near = k._offset(u, 20.0)
    complete &= _report_value("5a away full offset (back 25, down 6)",
                    abs(ofs_far[0] + 25.0) < 1e-9 and abs(ofs_far[2] - 6.0) < 1e-9,
                    f"scale={scale_far:.2f}")
    complete &= _report_value("linear between 5b terminal/melt",
                    0.2 < scale_middle < 0.8, f"35 m -> measurement {scale_middle:.2f}")
    complete &= _report_value("Exact zero in 5c melting range",
                    scale_near == 0.0 and np.allclose(ofs_near, 0.0),
                    "multiplication is done without offset")

    k0 = TrackingController(TrackingConfig())
    complete &= _report_value("5d offset defaults to ZERO (multiplication)",
                    np.allclose(k0._offset(u, 60.0)[0], 0.0))

    # yaw : ATC_ANG_YAW_P * ex , ceiling ATC_SLEW_YAW
    complete &= _report_value("5e yaw = 4.5 * ex", abs(k0._yaw(4.0) - 18.0) < 1e-9)
    complete &= _report_value("5f yaw ceiling 60 dps", abs(k0._yaw(40.0) - 60.0) < 1e-9)
    complete &= _report_value("5g ex<0 -> left", k0._yaw(-4.0) < 0.0)
    k_ablation = TrackingController(TrackingConfig(yaw_command_provide=False))
    complete &= _report_value("5h --no-yaw ablation", k_ablation._yaw(10.0) is None)
    return complete


# ========================================================= 6. state machine

def test_state_machine():
    """MISS/HIT: Should work with the SAME thresholds as MPC (common criteria)."""
    print("\n6. State machine (HIT / HIT / contact)")
    complete = True

    # (a) phase transitions
    k = TrackingController(TrackingConfig())
    for i, r in enumerate([80.0, 50.0, 44.0, 30.0, 21.0, 8.0]):
        k._state_machine(_measurement(r=r, t=i * 0.05), r, 10.0, 0.05)
    complete &= _report_value("6a CLOSURE -> TERMINAL -> IMPACT",
                    k.state_value == 'IMPACT' and k.impact_blend > 0.99,
                    f"case={k.state_value} mix={k.impact_blend:.2f}")

    # (b) MISS: range opening
    k = TrackingController(TrackingConfig())
    t = 0.0
    for r in list(np.linspace(60.0, 10.0, 40)) + list(np.linspace(10.0, 50.0, 40)):
        t += 0.05
        k._state_machine(_measurement(r=r, t=t), r, -5.0, 0.05)
    complete &= _report_value("6b MISS (range opening)", k.state_value == 'MISS',
                    k.miss_reason)

    # (c) ISC: timeout (engagement that never closes)
    k = TrackingController(TrackingConfig())
    t = 0.0
    for _ in range(300):
        t += 0.05
        k._state_machine(_measurement(r=70.0, t=t), 70.0, 0.0, 0.05)
        if k.state_value == 'MISS':
            break
    complete &= _report_value("6c WSC (timeout 8 s)",
                    k.state_value == 'MISS' and 'timeout' in k.miss_reason,
                    f"t={t:.1f} s")

    # (d) --no-miss ablation
    k = TrackingController(TrackingConfig(miss_mode=False))
    t = 0.0
    for r in list(np.linspace(60.0, 10.0, 40)) + list(np.linspace(10.0, 90.0, 60)):
        t += 0.05
        k._state_machine(_measurement(r=r, t=t), r, -5.0, 0.05)
    complete &= _report_value("6d --no-miss : MISS is not declared", k.state_value != 'MISS',
                    f"state={k.state_value}")

    # (e) CONTACT detection: vibe>15 AND measured range<3
    k = TrackingController(TrackingConfig())
    absent = k._impact_successful_control(_measurement(r=2.0, vibe=8.0), 2.0)
    absent2 = k._impact_successful_control(_measurement(r=20.0, vibe=30.0), 20.0)
    var = k._impact_successful_control(_measurement(r=1.2, vibe=22.0), 1.2)
    repeat = k._impact_successful_control(_measurement(r=1.0, vibe=25.0), 1.0)
    complete &= _report_value("6e contact detection (vibe + range, latch)",
                    absent is None and absent2 is None and var is not None
                    and repeat is None and k.hit_value,
                    var[1] if var else '')
    return complete


# ============================================= 6b. RANGE INDEPENDENCE (EVIDENCE)

def test_range_independence():
    """BY DEFAULT THE COMMAND IS RANGE INDEPENDENT -- algebraic proof + test.

    User's rule: range comes from GROUND DETECTION, WE DO NOT TRUST IT; The purpose of visual
    guidance is to eliminate the error of ground detection and see the target with one's own eyes.
    The question this test asks is: how OLD does the law get to the range?

    ALGEBRA (default: ofs=0, speed_source='ceiling', brake closed): error = r * u_los + 0 v = kp *
    error = kp*r * u_los 'ceiling': v = v * (V/|v|) = V * u_los <-- r FULLY SIMPLIFIED horizontal
    ceiling: |v_xy| = V*cos(eps) <= V <-- does not connect at all vertical clamp: v_z =
    clip(-V*sin(eps), ...) <-- only connected to eps So the command (ex, ey, yaw is the function of
    aim); IT NEVER ENTER RANGE. The range ONLY enters the WATCH/phase state machine -- so it is the
    REFEREE who decides "when to give up", NOT the controller input.

    This test verifies that claim by numbers and shows that it is BROKEN at the 'p' lever (where |v|
    = kp*r, so the range is directly on the accelerator)."""
    print("\n6b. Range independence (not relying on ground detection)")
    complete = True

    def _command_vec(config_value, r_measure, **kw):
        k = TrackingController(config_value)
        k.seed_value2({'cmd_vel_ned': [20.0, 0.0, 0.0]})
        # Styling trims the size in the first loop; It does not affect DIRECTION.
        return np.asarray(k.command_value(_measurement(r=r_measure, **kw)).vel_ned, float)

    # (a) DEFAULT: range changes by 6, command remains EXACTLY the same
    A = TrackingConfig()
    v1 = _command_vec(A, 10.0, ex=4.0, ey=-6.0)
    v2 = _command_vec(A, 60.0, ex=4.0, ey=-6.0)
    v3 = _command_vec(A, 200.0, ex=4.0, ey=-6.0)
    complete &= _report_value("6b-a default: command range INDEPENDENT",
                    np.allclose(v1, v2, atol=1e-12)
                    and np.allclose(v1, v3, atol=1e-12),
                    f"10 m: {np.round(v1, 4).tolist()} == 200 m: "
                    f"{np.round(v3, 4).tolist()}")

    # (b) same command when there is NO range (measurement None)
    k = TrackingController(TrackingConfig())
    k.seed_value2({'cmd_vel_ned': [20.0, 0.0, 0.0]})
    o = _measurement(r=None, ex=4.0, ey=-6.0)
    v_absent = np.asarray(k.command_value(o).vel_ned, float)
    complete &= _report_value("6b-b Same command WHEN THERE IS NO RANGE MEASUREMENT",
                    np.allclose(v1, v_absent, atol=1e-12),
                    f"{np.round(v_absent, 4).tolist()}")

    # (c) DISTURBED at lever 'p': there the range is directly on the accelerator pedal
    P = TrackingConfig(speed_source='p')
    p1 = _command_vec(P, 10.0, ex=4.0, ey=-6.0)
    p2 = _command_vec(P, 60.0, ex=4.0, ey=-6.0)
    complete &= _report_value("6b-c 'p' arm DEPENDS ON range (contrary evidence)",
                    not np.allclose(p1, p2, atol=1e-6),
                    f"|v| {float(np.linalg.norm(p1)):.2f} -> "
                    f"{float(np.linalg.norm(p2)):.2f} m/s")

    # (d) independence is BREAKED WHEN offset is ON (offset scales with range)
    O = TrackingConfig(ofs_backward_m=25.0, ofs_down_m=6.0)
    o1 = _command_vec(O, 20.0, ex=4.0, ey=-6.0)
    o2 = _command_vec(O, 60.0, ex=4.0, ey=-6.0)
    complete &= _report_value("6b-d offset ON -> connects to range (so 0)",
                    not np.allclose(o1, o2, atol=1e-6),
                    "There is no cost as the offset in the multiplication setting is 0")

    # (e) WHERE RANGE ENTERS: lone state machine. If we run the same measurement flow with two different
    # ranges, the commands should be the same but the situations should be different.
    def _states(r_multiplier):
        k = TrackingController(TrackingConfig())
        k.seed_value2({'cmd_vel_ned': [20.0, 0.0, 0.0]})
        states_value, commands = [], []
        for i in range(60):
            r_actual = 60.0 - i * 0.8
            c = k.command_value(_measurement(r=r_actual * r_multiplier, t=i * 0.05,
                               ex=2.0, ey=-4.0))
            states_value.append(k.state_value)
            commands.append(np.asarray(c.vel_ned, float).copy())
        return states_value, np.array(commands)

    d1, c1 = _states(1.0)
    d2, c2 = _states(0.5)       # range is reported as HALF
    complete &= _report_value("6b-e when the range is broken, the COMMAND is the same, the SITUATION changes",
                    np.allclose(c1, c2, atol=1e-12) and d1 != d2,
                    f"phase switch {d1.count('IMPACT')} -> {d2.count('IMPACT')} loop")
    return complete


# ========================================================= 7. Command path entire

def test_command_path():
    """command() three to three: from measurement to Command, are the signs correct."""
    print("\n7. Command path (triple)")
    complete = True
    k = TrackingController(TrackingConfig())
    k.seed_value2({'cmd_vel_ned': [17.0, 0.0, 0.0]})

    # (a) target straight ahead, equal altitude -> command pure north; SIZE limited to shaping in first
    # cycle (seed 17.0 + 3.0*dt) -- NO steps.
    c = k.command_value(_measurement(ex=0.0, ey=0.0, r=40.0, t=0.0, dt=0.05))
    complete &= _report_value("7a straight ahead -> pure north, NO steps in first loop",
                    c.vel_ned[0] > 0.0 and abs(c.vel_ned[1]) < 1e-6
                    and abs(c.vel_ned[2]) < 1e-6
                    and abs(c.vel_ned[0] - 17.15) < 1e-6,
                    f"{np.round(c.vel_ned, 2).tolist()}")
    # 130 step = 6.5 s: BEFORE the WSC timeout (8 s), the forming reaches the ceiling (17 + 3*6.5 = 36.5 >
    # 35).
    for i in range(1, 130):
        c = k.command_value(_measurement(ex=0.0, ey=0.0, r=40.0, t=i * 0.05, dt=0.05))
    complete &= _report_value("7a2 ceiling after shaping ( 35 m/s )",
                    abs(c.vel_ned[0] - 35.0) < 1e-6, f"{c.vel_ned[0]:.2f} m/s")

    # (b) target UP (ey<0) -> CLIMB command (vz<0)
    k.reset_value()
    c = k.command_value(_measurement(ex=0.0, ey=-12.0, r=30.0, t=0.0))
    complete &= _report_value("7b target above -> climbing", c.vel_ned[2] < -1.0,
                    f"vz={c.vel_ned[2]:.2f} m/s")

    # (c) target BELOW (ey>0) -> descent, but limited to 5 m/s
    k.reset_value()
    c = k.command_value(_measurement(ex=0.0, ey=+30.0, r=30.0, t=0.0))
    complete &= _report_value("7c target below -> descent (<=5 m/s)",
                    0.0 < c.vel_ned[2] <= 5.0 + 1e-9, f"vz={c.vel_ned[2]:.2f}")

    # (d) The instruction yaw has the same sign as ex
    k.reset_value()
    c = k.command_value(_measurement(ex=8.0, r=40.0))
    complete &= _report_value("7d yaw command (+ex -> +yaw)",
                    c.yaw_rate_dps is not None and c.yaw_rate_dps > 0,
                    f"{c.yaw_rate_dps:.1f} dps")

    # (e) Drop flag on MISS + braked glide
    k = TrackingController(TrackingConfig())
    k.seed_value2(None)
    t = 0.0
    last_value = None
    for r in list(np.linspace(60.0, 10.0, 40)) + list(np.linspace(10.0, 60.0, 60)):
        t += 0.05
        last_value = k.command_value(_measurement(r=r, t=t, vel=(30.0, 0.0, 0.0), area_value=(40.0 - r * 0.4)))
        if last_value.release_value:
            break
    complete &= _report_value("7e HISTORY -> release + glide (NOT zero)",
                    last_value is not None and last_value.release_value
                    and float(np.linalg.norm(last_value.vel_ned)) > 10.0,
                    f"|v|={float(np.linalg.norm(last_value.vel_ned)):.1f} m/s "
                    f"reason={last_value.release_reason[:40]}")

    # (f) Does the CONTACT event get stuck in the Command?
    k = TrackingController(TrackingConfig())
    k.seed_value2(None)
    k.command_value(_measurement(r=30.0, t=0.0))
    c = k.command_value(_measurement(r=1.5, t=0.05, vibe=25.0))
    complete &= _report_value("7f impact_successful event in Command",
                    c.event_value == 'impact_successful', c.event_detail[:50])
    return complete


# ========================================================= 8. closed loop

def scenario_run(route="straight", handoff="tail", config_value=None, duration_value=25.0, seed_value=3,
                loop_hz=20.0, target_speed_mps=20.0, jitter=True,
                collision_m=2.0, miss_finish=True, target_altitude_m=60.0,
                loss_finish_s=1.5, range_disruption=None, gimbal_camera=None):
    """mpc_test.TrackingController version of scenario_run (same engine, same output).

    Engine mpc_test. Simulation: point-mass fighter, REAL virtual gimbal, LPF of the
    skeleton/clamp/acceleration chain. So the numbers here can be directly compared to the numbers
    of MPC produced with the same function."""
    # gimbal_camera=None -> engine own default (True in gimbal branch). By issuing False the OLD
    # body-fixed physics returns; essential to SEPARATE law change from physics change (see
    # ARDUPILOT_TRACKING.md 6e).
    ek = {} if gimbal_camera is None else {'gimbal_camera': bool(gimbal_camera)}
    b = Simulation(route=route, handoff=handoff, seed_value=seed_value, loop_hz=loop_hz,
                 target_altitude_m=target_altitude_m, target_speed_mps=target_speed_mps, **ek)
    k = TrackingController(config_value or TrackingConfig())
    k.seed_value2({'cmd_vel_ned': b.v.copy().tolist()})
    rng = np.random.default_rng(seed_value + 100)

    t = 0.0
    min_r = 1e9
    r0 = None
    loss_value = 0
    count_value = 0
    loss_consecutive = 0.0
    min_r_fresh = 1e9         # Closest range reached while STILL SEEING
    v_last = b.v.copy()
    last_request = None
    # SEPARATE RNG TO DISTORTOR: main rng produces loop jitter (dt); If the jammer pulls from it, the
    # jitter array shifts and the ORBIT changes -- so what reads as "noise disturbed range" is actually a
    # different dt array. This trap was fallen once (the noise lever showed 1.60 instead of 1.35 ); makes
    # separate seed arms EXACTLY comparable.
    disturbance_rng = np.random.default_rng(seed_value + 900)
    cmd_speeds = []
    closures = []
    miss_t = None
    miss_reason = ''
    finish = 'duration_elapsed'
    while t < duration_value:
        dt = b.dt_nom
        if jitter:
            dt = b.dt_nom * (1.0 + 0.25 * rng.random())
            if rng.random() < 0.04:
                dt = b.dt_nom * (2.0 + 1.0 * rng.random())
        o, visible, r = b.measurement(dt)
        if range_disruption is not None:
            # RANGE DISTURBANCE: only contaminates the MEASUREMENT; The ACTUAL r returned by b.metric (for
            # metrics) remains untouched. This is the right place to emulate ground detection error -- common
            # engine
            # (mpc_test.Simulation) hic dokunulmuyor.
            o.range_m_value = range_disruption(o.range_m_value, t, disturbance_rng)
        if r0 is None:
            r0 = r
        min_r = min(min_r, r)
        count_value += 1
        if visible:
            loss_consecutive = 0.0
            min_r_fresh = min(min_r_fresh, r)
            c = k.command_value(o)
            request_value = np.asarray(c.vel_ned, dtype=float)
            yaw_cmd = c.yaw_rate_dps
            last_request = request_value.copy()
            cmd_speeds.append(float(np.linalg.norm(request_value)))
            if getattr(c, 'release_value', False) and miss_t is None:
                miss_t, miss_reason = t, c.release_reason
                if miss_finish:
                    finish = 'miss_value'
                    break
        else:
            loss_value += 1
            loss_consecutive += dt
            # missing behavior of SKELETON (visual_base.run): age <= 0.7 s -> controller is already called
            # (above) 0.7 < age <= 1.7 s -> LAST command is KEPT (except yaw) age > 1.7 s -> GLIding: command =
            # MEASURED speed (acceleration 0)
            if loss_consecutive <= 1.0 and last_request is not None:
                request_value = last_request
            else:
                request_value = b.v.copy()
            yaw_cmd = None
        # closing speed (ANALYSIS): relative speed along LOS
        d = b.q - b.p
        n = float(np.linalg.norm(d))
        if n > 1e-6:
            closures.append(float((b.v - np.array(
                [b.target_speed * math.cos(b.target_direction),
                 b.target_speed * math.sin(b.target_direction), 0.0])) @ (d / n)))
        b.advance(request_value, yaw_cmd, dt)
        t += dt
        v_last = b.v.copy()
        if collision_m > 0.0 and r <= collision_m:
            finish = 'collision'
            break
        if b.altitude_value < 5.0:
            finish = 'ground_contact'
            break
        if loss_consecutive > loss_finish_s:
            # SAME rule as mpc_test (LOSS_FINISH_S): when it is left out of frame for this long, the decision
            # maker gives the authority back to the positioner, that is, THE VISUAL SEGMENT ENDS. Continuing the
            # run would be blindly measuring glide as "steering quality".
            finish = 'framing_loss'
            break
    return {
        'route': route, 'handoff': handoff, 'seed_value': seed_value, 'duration_value': t,
        'r0': r0, 'min_r': min_r, 'min_r_fresh': min_r_fresh, 'finish': finish,
        'loss_pct': 100.0 * loss_value / max(count_value, 1),
        'cmd_p95': float(np.percentile(cmd_speeds, 95)) if cmd_speeds else 0.0,
        'cmd_max': float(np.max(cmd_speeds)) if cmd_speeds else 0.0,
        'closure_mean': float(np.mean(closures)) if closures else 0.0,
        'miss_t': miss_t, 'miss_reason': miss_reason,
        'min_altitude': b.min_altitude, 'state_value': k.state_value, 'hit_value': k.hit_value,
        'speed_last': float(np.linalg.norm(v_last)),
    }


def test_disabled_loop(fast_value=False):
    """Seven scenarios. Thresholds ~%30 above MEASURED values: these are REGRESSION WATCHMEN, not targets
(see ARDUPILOT_TRACKING.md benchmark chart for MPC's numbers with the same engine).

    The ending 'framing_loss' is NOT a FAILURE, but a measured result: when 1.5 s remain out of
    frame, the decision maker hands power back to the position (same rule as mpc_test)."""
    print("\n8. Closed loop (mpc_test.Simulation engine, 1.5 s framing rule)")
    complete = True
    seeds = (3, 11) if fast_value else (3, 11, 29, 47)
    scenarios = [
        ("static", dict(route="straight", target_speed_mps=0.0, handoff="tail"), 3.0),
        ("straight/tail", dict(route="straight", handoff="tail"), 3.0),
        ("straight/crossing", dict(route="straight", handoff="crossing"), 6.0),
        ("ellipse/tail", dict(route="ellipse", handoff="tail"), 4.0),
        ("ellipse/crossing", dict(route="ellipse", handoff="crossing"), 9.0),
        ("wanderer/tail", dict(route="wanderer", handoff="tail"), 9.0),
        ("wanderer/crossing", dict(route="wanderer", handoff="crossing"), 24.0),
    ]
    for label_item, kw, threshold_value in scenarios:
        kw.setdefault('target_speed_mps', 21.05)
        minima, finishes, losses = [], [], []
        for seed_value in seeds:
            s = scenario_run(config_value=TrackingConfig(), seed_value=seed_value, duration_value=30.0, **kw)
            minima.append(s['min_r'])
            finishes.append(s['finish'])
            losses.append(s['loss_pct'])
        median_value = float(np.median(minima))
        print(f"      {label_item:16s} min median= {median_value:6.2f} m  "
              f"loss= {float(np.mean(losses)):4.1f} %  "
              f"end={','.join(b[:4] for b in finishes)}")
        complete &= _report_value(f"8-{label_item}: min range median < {threshold_value:.0f} m",
                        median_value < threshold_value, f"{median_value:.2f} m")
    return complete


def _disturbances():
    """Real-life degradation patterns of ground detection.

    All measurement ONLY. Contaminates range_m_value; view (ex/ey) remains CLEAR -- that's the channel
    the user trusts anyway."""
    state_value = {}

    def frozen(r, t, rng):
        if r is None:
            return None
        state_value.setdefault('initial', r)
        return state_value['initial']

    return [
        ('clean            ', lambda r, t, g: r),
        ('bias x0.5    ', lambda r, t, g: None if r is None else 0.5 * r),
        ('bias x2.0    ', lambda r, t, g: None if r is None else 2.0 * r),
        ('bias +20 m   ', lambda r, t, g: None if r is None else r + 20.0),
        ('noise %30      ', lambda r, t, g: None if r is None
         else max(0.5, r * (1.0 + 0.30 * g.normal()))),
        ('frozen (initial value)', frozen),
        ('dropout %50        ', lambda r, t, g: None if (r is None or g.random() < 0.5)
         else r),
        ('NO RANGE       ', lambda r, t, g: None),
    ]


def test_range_degradation(fast_value=False):
    """Pollute the range IN CLOSED LOOP: how far is the law being broken?

    6b showed algebraically that the command is range independent. The question posed here is
    practical: IF the ground detection is INCORRECT (no bias/noise/disconnection/nothing) how much
    does the RESULT OF THE ENGAGEMENT change? Expectation: the homing flies exactly the same, the
    only thing that changes is when the SQUARE referee blows the whistle."""
    print("\n11. Durability under range degradation (ground detection error)")
    complete = True
    seeds = (3,) if fast_value else (3, 11, 29)
    # LAST SCENARIO CONSCIOUS: ends with ellipse/cross LISA (see test 8). The first three test the command
    # path, the last the REFEREE -- the range only works there, so that's the only place the distortion
    # will appear.
    scenarios = [("straight/tail", dict(route="straight", handoff="tail")),
                  ("ellipse/tail", dict(route="ellipse", handoff="tail")),
                  ("wanderer/tail", dict(route="wanderer", handoff="tail")),
                  ("ellipse/crossing(MISS)", dict(route="ellipse", handoff="crossing"))]
    floor_value = {}
    result_value = {}
    for label_item, disturbance in _disturbances():
        row_value = []
        for sad, kw in scenarios:
            minima, finishes = [], []
            for seed_value in seeds:
                s = scenario_run(config_value=TrackingConfig(), seed_value=seed_value, duration_value=30.0,
                                target_speed_mps=21.05, range_disruption=disturbance, **kw)
                minima.append(s['min_r'])
                finishes.append(s['finish'][:4])
            row_value.append((sad, float(np.median(minima)), finishes))
        result_value[label_item.strip()] = row_value
        if label_item.startswith('clean'):
            floor_value = {s: m for s, m, _ in row_value}
        print(f"      {label_item}  " + "  ".join(
            f"{s}={m:6.2f}[{','.join(b)}]" for s, m, b in row_value))

    # CRITERIA: min range of broken arms should not exceed 2 times of clean arm.
    for label_item, row_value in result_value.items():
        if label_item.startswith('clean'):
            continue
        poor = [f"{s} {m:.1f} vs {floor_value[s]:.1f}"
                for s, m, _ in row_value if m > max(2.0 * floor_value[s], floor_value[s] + 3.0)]
        complete &= _report_value(f"11-{label_item}: distortion limited relative to clear",
                        not poor, '; '.join(poor) if poor else 'all on tape')
    return complete


def test_evaluator_range_sensitivity():
    """WHERE RANGE STILL WORKS: The range arms of the MISS referee.

    Testing showed that the 11 command path was range independent, but in those scenarios the SCA
    always fired WITH TIMEOUT -- so range-dependent arms (range opening / absolute range) were never
    tested. Here those arms are tested DIRECTLY: a synthetic 'close then rush' range profile is
    given to the referee and WHEN the SCA sounds under each distortion.

    MEASURED (my guess was wrong, the count is right): the referee slips BOTH types of bias -- x0.5
    -> 70.6 m | clean 18.7 m | +20 m -> 40.7 m | x2.0 -> 25.7 m Reason: rule is not pure DIFFERENCE
    rule; difference tests (r > best_candidate + 30) nested with ABSOLUTE gates (miss_transition_arm_m=12,
    miss_arm_m=45, miss_absolute_m=120). When the additive bias shifts these doors, it changes which
    ARM fires (switching arm -> normal arm), so the result also changes.

    Conclusion: the command path is completely independent of range (test 11), but the REFEREE is
    not. The way to save the referee is to throw away the absolute gates and switch to the RATIO
    base -- since sqrt(field) ~ 1/r, the bbox field gives this WITHOUT CALIBRATION
    (bkz. miss_source='area_value')."""
    print("\n12. Arbiter (MISS) range sensitivity -- only remaining dependency")
    complete = True

    def _fire_instantaneous(multiplier=1.0, addition=0.0):
        """r: profile 60 -> 10 -> 80. Returns the ACTUAL range at which the MISS fires."""
        k = TrackingController(TrackingConfig(miss_time_timeout_s=1e9))  # timer OFF
        t = 0.0
        profile = list(np.linspace(60.0, 10.0, 60)) + list(np.linspace(10.0, 80.0, 90))
        for r_ger in profile:
            t += 0.05
            r_reported = r_ger * multiplier + addition
            k._state_machine(_measurement(r=r_reported, t=t), r_reported, -5.0, 0.05)
            if k.state_value == 'MISS':
                return r_ger, k.miss_reason
        return None, ''

    floor_value, reason_value = _fire_instantaneous()
    complete &= _report_value("12a clean: 'range opening' arm fires",
                    floor_value is not None and 'opening' in reason_value,
                    f"real {floor_value:.1f} in m -- {reason_value[:44]}")

    r_ek, _ = _fire_instantaneous(addition=20.0)
    r_x2, _ = _fire_instantaneous(multiplier=2.0)
    r_x05, _ = _fire_instantaneous(multiplier=0.5)
    all_value = [x for x in (floor_value, r_ek, r_x2, r_x05) if x is not None]
    propagation = (max(all_value) - min(all_value)) if len(all_value) == 4 else float('inf')
    complete &= _report_value("12b referee SLIDES from range bias (measured deficit)",
                    propagation > 5.0,
                    f"x0. 5 {r_x05:.1f} | clean {floor_value:.1f} | +20m {r_ek:.1f} | "
                    f"x2. 0 {r_x2:.1f} m (span {propagation:.1f} m)")

    # VISUAL REFEREE is in the same profile: field bbox is produced consistent with range (s = sqrt(field)
    # ~ 1/r), while range is DISTORTED. Since it is odds based, the referee should not see the breakdown.
    def _fire_instantaneous_area(multiplier=1.0, addition=0.0):
        k = TrackingController(TrackingConfig(miss_source='area_value',
                                     miss_time_timeout_s=1e9))
        t = 0.0
        profile = list(np.linspace(60.0, 10.0, 60)) + list(np.linspace(10.0, 80.0, 90))
        for r_ger in profile:
            t += 0.05
            edge = 1000.0 / r_ger          # bbox edge ~ 1/r (real geometry)
            o = _measurement(r=r_ger * multiplier + addition, t=t, area_value=edge)
            area_value, area_rate = k._area_update(o, 0.05)
            k._state_machine(o, r_ger * multiplier + addition, area_rate, 0.05)
            if k.state_value == 'MISS':
                return r_ger, k.miss_reason
        return None, ''

    a_floor, a_reason = _fire_instantaneous_area()
    a_ek, _ = _fire_instantaneous_area(addition=20.0)
    a_x2, _ = _fire_instantaneous_area(multiplier=2.0)
    a_x05, _ = _fire_instantaneous_area(multiplier=0.5)
    a_all = [x for x in (a_floor, a_ek, a_x2, a_x05) if x is not None]
    a_propagation = (max(a_all) - min(a_all)) if len(a_all) == 4 else float('inf')
    complete &= _report_value("12c VISUAL referee (miss_source='area') range INDEPENDENT",
                    a_propagation < 1e-9,
                    f"on all four arms {a_floor:.1f} m -- {a_reason[:40]}"
                    if a_floor else "ateslemedi")
    complete &= _report_value("12d visual referee fires at reasonable range",
                    a_floor is not None and 12.0 < a_floor < 45.0,
                    f"{a_floor:.1f} m (range judge clear {floor_value:.1f} m)"
                    if a_floor else '')
    return complete


def test_visual_evaluator(fast_value=False):
    """VISUAL REFEREE: What happens when you disable the range completely?

    Test 11: command path is range independent. Test 12: NOT referee. Two questions here: (a) COST:
    does switching the referee from range to area disrupt the result of the engagement? (b) GAIN:
    with the 'area' referee does the ENTIRE system work without range? (So ​​if we cut the range
    cable, will the vehicle fly the same?)"""
    print("\n 13. Visual referee ( miss_source =' area_value ') -- rangeless system")
    complete = True
    seeds = (3,) if fast_value else (3, 11, 29)
    sen = [("straight/tail", dict(route="straight", handoff="tail")),
           ("straight/crossing", dict(route="straight", handoff="crossing")),
           ("ellipse/tail", dict(route="ellipse", handoff="tail")),
           ("ellipse/crossing", dict(route="ellipse", handoff="crossing")),
           ("wand/tail", dict(route="wanderer", handoff="tail")),
           ("wand/crossing", dict(route="wanderer", handoff="crossing"))]

    def _run(config_value, kw, disturbance=None):
        m = []
        for seed_value in seeds:
            s = scenario_run(config_value=config_value, seed_value=seed_value, duration_value=30.0,
                            target_speed_mps=21.05, range_disruption=disturbance, **kw)
            m.append(s['min_r'])
        return float(np.median(m))

    # (a) COST: range referee vs visual referee, with CLEAN range. GIMBAL BRANCH: the lock was made
    # ONE-WAY. Apparent aspect peak in gimbal physics was timed differently and the visual judge gave
    # BETTER CPA in wand/diagonal than the range judge (11.5 vs 13.2 m); |difference| His criterion was
    # that this improvement was a "price" and fell. The safety intent is the same: the visual referee
    # should NOT worsen the CPA.
    cost_max = 0.0
    for label_item, kw in sen:
        a1 = _run(TrackingConfig(), kw)
        a2 = _run(TrackingConfig(miss_source='area_value'), kw)
        cost_max = max(cost_max, a2 - a1)
        print(f"      {label_item:13s} range judge={a1:6.2f} visual={a2:6.2f}")
    complete &= _report_value("13a visual referee has no COST (CPA does not get worse)",
                    cost_max < 0.05,
                    f"greatest deterioration {cost_max:+.3f} m")

    # (b) GAIN: visual referee + NO RANGE -> still the same
    absent = lambda r, t, g: None                                   # noqa: E731
    difference_max = 0.0
    for label_item, kw in sen:
        a1 = _run(TrackingConfig(miss_source='area_value'), kw)
        a2 = _run(TrackingConfig(miss_source='area_value'), kw, disturbance=absent)
        difference_max = max(difference_max, abs(a1 - a2))
    complete &= _report_value("13b visual referee + NO RANGE: system flies EXACTLY",
                    difference_max < 1e-9,
                    f"6 scenario x {len(seeds)} seed, the biggest difference "
                    f"{difference_max:.2e} m")

    # (c) Quality gate: small bbox MUST NOT enter the referee
    k = TrackingController(TrackingConfig(miss_source='area_value'))
    for i in range(30):                       # 5 px bbox is below the gate
        o = _measurement(r=200.0, t=i * 0.05, area_value=5.0)
        area_value, ah = k._area_update(o, 0.05)
        k._state_machine(o, 200.0, ah, 0.05)
    complete &= _report_value("13c quality door: 5 px bbox does not dirty the top",
                    k.s_peak == 0.0 and k.s_lpf is None,
                    f"s_peak={k.s_peak:.1f} small_counter={k._area_small_counter}")

    # (d) 'too small' arm = no-range equivalent of miss_absolute_m
    for i in range(30, 60):
        o = _measurement(r=200.0, t=i * 0.05, area_value=5.0)
        area_value, ah = k._area_update(o, 0.05)
        k._state_machine(o, 200.0, ah, 0.05)
    complete &= _report_value("13d persistently small target -> MISS (without reading range)",
                    k.state_value == 'MISS' and 'too small' in k.miss_reason,
                    k.miss_reason)
    return complete


def test_progress_clock(fast_value=False):
    """What happens when TIMEOUT is connected to the 'advance' clock?

    Deficit measured in the offline trace: in the ellipse/diagonal the range decreased to 45 -> 19
    m, the closure increased with each quarter (+7.7 m/s) and at that very moment 8 s WALL CLOCK was
    filled and a WATCH was declared -- the winning engagement was cut off.

    On the 'advance' hand, the clock only ticks when the visible area of ​​the target is NOT
    enlarging. Two things must be verified at once: (a) GAIN: the interruption must end when
    closing, (b) SAFETY: the desperate engagement must STILL end (or the vehicle will chase in vain
    forever) -- the absolute ceiling guarantees this."""
    print("\n14. Progress clock (do not ring when timeout is closing)")
    complete = True
    seeds = (3,) if fast_value else (3, 11, 29)
    sen = [("straight/tail", dict(route="straight", handoff="tail")),
           ("ellipse/tail", dict(route="ellipse", handoff="tail")),
           ("ellipse/crossing", dict(route="ellipse", handoff="crossing")),
           ("wand/crossing", dict(route="wanderer", handoff="crossing"))]

    def _run(config_value, kw, **ek):
        m = []
        for seed_value in seeds:
            s = scenario_run(config_value=config_value, seed_value=seed_value, duration_value=40.0,
                            target_speed_mps=ek.pop('target_speed_mps', 21.05),
                            **kw, **ek)
            m.append(s)
        return m

    gain = {}
    for label_item, kw in sen:
        d = float(np.median([s['min_r'] for s in _run(
            TrackingConfig(miss_time_source='straight'), kw)]))
        i = float(np.median([s['min_r'] for s in _run(
            TrackingConfig(miss_time_source='progress'), kw)]))
        gain[label_item] = (d, i)
        print(f"      {label_item:13s} flat clock={d:6.2f} advance={i:6.2f}  "
              f"{'GAIN' if i < d - 0.5 else ('equal' if abs(i - d) < 0.5 else 'LOSS')}")
    complete &= _report_value("14a There is no REGRESSION in any scenario",
                    all(i <= d + 0.5 for d, i in gain.values()),
                    "worst difference "
                    f"{max(i - d for d, i in gain.values()):+.2f} m")
    complete &= _report_value("Big win on 14b ellipse/diagonal",
                    gain["ellipse/crossing"][1] < 0.5 * gain["ellipse/crossing"][0],
                    f"{gain['ellipse/crossing'][0]:.2f} -> "
                    f"{gain['ellipse/crossing'][1]:.2f} m")

    # (c) SAFETY: the target is FASTER than us -> we can't close at all. Since the clock will not be able
    # to see the progress, normal operations and WHS should be declared.
    k = TrackingController(TrackingConfig(miss_time_source='progress'))
    k.seed_value2(None)
    t = 0.0
    for i in range(400):                      # 20 s, range always opening
        t += 0.05
        r = 40.0 + i * 0.05
        o = _measurement(r=r, t=t, area_value=max(1.0, 1000.0 / r))
        area_value, ah = k._area_update(o, 0.05)
        k._state_machine(o, r, ah, 0.05)
        if k.state_value == 'MISS':
            break
    complete &= _report_value("14c non-closing engagement STILL ends",
                    k.state_value == 'MISS' and t < 12.0,
                    f"t={t:.1f} s -- {k.miss_reason[:44]}")

    # (d) SAFETY- 2: the area grows FRICTIONLESS but we never crash (pathological) -> absolute ceiling
    # should come into play.
    k = TrackingController(TrackingConfig(miss_time_source='progress',
                                 miss_absolute_duration_s=12.0))
    k.seed_value2(None)
    t = 0.0
    for i in range(600):
        t += 0.05
        # USSEL approach: r = 60*exp(-t/30). Relative area growth EVERY MOMENT 2/30 = 0.067 1/s (above
        # threshold 0.05) but range DOES NOT go to ZERO in finite time -> advance clock never expires. The
        # only stopping thing is the absolute ceiling; This is exactly what the test tests.
        r = 60.0 * math.exp(-t / 30.0)
        o = _measurement(r=r, t=t, area_value=1000.0 / r)
        area_value, ah = k._area_update(o, 0.05)
        k._state_machine(o, r, ah, 0.05)
        if k.state_value == 'MISS':
            break
    complete &= _report_value("14d absolute ceiling (safety valve) works",
                    k.state_value == 'MISS' and t < 16.0,
                    f"t={t:.1f} s -- {k.miss_reason[:44]}")
    return complete


def test_ablations(fast_value=False):
    """What the knobs of the law do in closed loop (A/B, same seed)."""
    print("\n9. Ablations (straight route, target 21.05 m/s, seed 3)")
    complete = True
    VARS = "DEFAULT (roof, classic, brake off)"
    arms = [
        (VARS, TrackingConfig()),
        ("pure mode_follow ('p', kp 1.0 )", TrackingConfig(speed_source='p')),
        ("pure mode_follow + AP kp= 0.1", TrackingConfig(speed_source='p', kp=0.1)),
        ("brake ON (AP 'stay next to')", TrackingConfig(braking='ap')),
        ("position ( Copter >= 4.5 )", TrackingConfig(law='poscon')),
        ("standoff offset 25 / 6", TrackingConfig(ofs_backward_m=25.0, ofs_down_m=6.0)),
        ("yaw ablation ( --no-yaw )", TrackingConfig(yaw_command_provide=False)),
        ("acceleration shaping OFF", TrackingConfig(acceleration_shaping_mps2=0.0)),
    ]
    result_value = {}
    for label_item, config_value in arms:
        s = scenario_run(route="straight", handoff="tail", config_value=config_value, seed_value=3,
                        duration_value=30.0, target_speed_mps=21.05)
        result_value[label_item] = s
        print(f"      {label_item:42s} min={s['min_r']:6.2f} m end={s['finish']:10s}"
              f"  shutdown = {s['closure_mean']:+5.1f} cmd_p95 = {s['cmd_p95']:5.1f}"
              f"  loss= {s['loss_pct']:4.1f} %")
    complete &= _report_value("9a pure 'p' arm cannot close (balance distance)",
                    result_value["pure mode_follow ('p', kp 1.0 )"]['min_r']
                    > 4.0 * result_value[VARS]['min_r'],
                    "speed_source decision is in closed loop")
    complete &= _report_value("9b AP kp=0.1 never closes the range",
                    result_value["pure mode_follow + AP kp= 0.1"]['min_r'] > 25.0)
    complete &= _report_value("9c brake ON kills closing",
                    result_value["brake ON (AP 'stay next to')"]['min_r']
                    > result_value[VARS]['min_r'],
                    "Closed loop proof of deviation (3)")
    # GIMBAL BRANCH: became the framing justification for sculpting (acceleration -> pitch -> FIXED camera
    # swing chain broken; measured: loss in both arms %0). The lock is turned to ABSOLUTE health, which
    # preserves gimbal gain: framing must be maintained and shuttering must persist, with or without
    # shaping. If it is broken, either the facility gimbal model or the constraint layer has receded.
    complete &= _report_value("In 9D gimbal physics, the frame is preserved without shaping",
                    result_value["acceleration shaping OFF"]['loss_pct'] < 5.0
                    and result_value[VARS]['loss_pct'] < 5.0
                    and result_value["acceleration shaping OFF"]['min_r'] < 3.0,
                    f"lost %{result_value[VARS]['loss_pct']:.1f}/ "
                    f"%{result_value['acceleration shaping OFF']['loss_pct']:.1f}, "
                    f"min {result_value['acceleration shaping OFF']['min_r']:.2f} m")
    return complete


def test_duration():
    """Loop cost: this law should be negligible according to the solver of MPC."""
    print("\n Costs the 10th loop")
    k = TrackingController(TrackingConfig())
    k.seed_value2(None)
    o = _measurement(ex=3.0, ey=-8.0, r=35.0)
    for i in range(50):                      # warmup
        o.t = i * 0.05
        k.command_value(o)
    t0 = time.perf_counter()
    N = 2000
    for i in range(N):
        o.t = 10.0 + i * 0.05
        k.command_value(o)
    us = (time.perf_counter() - t0) / N * 1e6
    return _report_value("10a command() < 200 us", us < 200.0, f"{us:.1f} us/loop "
                  f"(MPC solver p95 ~13000 us)")


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--fast-value', action='store_true',
                   help='single seed in closed loop tests')
    args = p.parse_args()
    print("=" * 74)
    print("tracking_guidance.py -- ArduPilot FOLLOW law tests")
    print("=" * 74)
    test_motor_seal()
    test_sqrt_controller()
    test_target_estimation()
    test_speed_law()
    test_kp_rationale()
    test_offset_and_yaw()
    test_state_machine()
    test_range_independence()
    test_command_path()
    test_disabled_loop(args.fast_value)
    test_range_degradation(args.fast_value)
    test_evaluator_range_sensitivity()
    test_visual_evaluator(args.fast_value)
    test_progress_clock(args.fast_value)
    test_ablations(args.fast_value)
    test_duration()
    print("\n" + "=" * 74)
    print(f"RESULT: {len(PASS)}/{len(PASS) + len(FAILED)} passed")
    if FAILED:
        for label_item in FAILED:
            print(f"  REQUIRED: {label_item}")
        sys.exit(1)
    print("ALL TESTS PASSED")


if __name__ == '__main__':
    main()
